apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-container
        image: kkaggarwal/user-service:0.0.3
        ports:
        - containerPort: 8080  